# Generated by Django 5.1.4 on 2025-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('Senior Accountant', 'Senior Accountant'), ('Marketing Manager', 'Marketing Manager'), ('Junior Accountant', 'Junior Accountant')], max_length=100)),
                ('experience', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
