# Generated by Django 5.1.4 on 2025-01-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeSubmission',
            new_name='Carrier',
        ),
    ]
