# Generated by Django 5.1.4 on 2025-01-05 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_rename_resumesubmission_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
