# Generated by Django 5.1.4 on 2025-01-16 13:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=tinymce.models.HTMLField(),
        ),
    ]
